name             'sagecrmenbuwebservices'
maintainer       'Taliesin Sisson'
maintainer_email 'taliesins@yahoo.com'
license          'All rights reserved'
description      'Installs/Configures sagecrm enbu webservices'
long_description 'Installs/Configures sagecrm enbu webservices'

version          '0.1.0'

depends 'webpi'
depends 'database'
depends 'windows'
depends 'ssl_certificate'
depends 'autoit'
depends 'windows_autologin'
depends 'iis'